// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkcT6pY9MvV6AnTI-DODhum24XBjoUihw',
    appId: '1:983811538149:web:4919e59c9855c76f90a80c',
    messagingSenderId: '983811538149',
    projectId: 'gecon-flutter',
    authDomain: 'gecon-flutter.firebaseapp.com',
    storageBucket: 'gecon-flutter.appspot.com',
    measurementId: 'G-S89HZTDZ45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWknV4mqrIyqvxegNp6w4Xnjg9aoODfjE',
    appId: '1:983811538149:android:2316cfa2881d8fab90a80c',
    messagingSenderId: '983811538149',
    projectId: 'gecon-flutter',
    storageBucket: 'gecon-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB704NMHz6PZBvXXwipZOcSYpB5KFaTNM',
    appId: '1:983811538149:ios:43a7acea741b6ccb90a80c',
    messagingSenderId: '983811538149',
    projectId: 'gecon-flutter',
    storageBucket: 'gecon-flutter.appspot.com',
    iosBundleId: 'com.example.dartAppVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB704NMHz6PZBvXXwipZOcSYpB5KFaTNM',
    appId: '1:983811538149:ios:5d151502e1d7800890a80c',
    messagingSenderId: '983811538149',
    projectId: 'gecon-flutter',
    storageBucket: 'gecon-flutter.appspot.com',
    iosBundleId: 'com.example.dartAppVersion.RunnerTests',
  );
}
